# Generated by Django 2.2.7 on 2019-11-20 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stripeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cinema name')),
                ('seating_capacity', models.CharField(max_length=200, verbose_name='Seating capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField(verbose_name='Born Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Matinees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(verbose_name='DateTime')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvtheater.Cinemas', verbose_name='Cinema')),
            ],
            options={
                'ordering': ['data_time'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Movie name')),
                ('imdbid', models.CharField(blank=True, max_length=15, null=True, verbose_name='movie id')),
                ('release_date', models.CharField(max_length=4, verbose_name='Release date')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode/', verbose_name='QR code')),
                ('state', models.BooleanField(default=False, verbose_name='It was used')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvtheater.Clients', verbose_name='Client')),
                ('matinee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='mvtheater.Matinees', verbose_name='Matinee')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='stripeapp.Transaction')),
            ],
            options={
                'ordering': ['matinee'],
            },
        ),
        migrations.AddField(
            model_name='matinees',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvtheater.Movies', verbose_name='Movie name'),
        ),
    ]
