# Generated by Django 2.2.7 on 2019-11-20 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100)),
                ('cc_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\d*$')], verbose_name='Credit Card number')),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d*$')], verbose_name='CVV')),
                ('exp_date', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d*$')], verbose_name='Expiration date')),
                ('amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=150, null=True)),
                ('object', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_refunded', models.IntegerField(blank=True, null=True)),
                ('funding', models.CharField(blank=True, max_length=30, null=True)),
                ('balance_transaction', models.CharField(blank=True, max_length=60, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('paid', models.BooleanField()),
                ('payment_method', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1_check', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=50, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('address_zip_check', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('cvc_check', models.CharField(blank=True, max_length=10, null=True)),
                ('dynamic_last4', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_month', models.PositiveIntegerField()),
                ('exp_year', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(blank=True, max_length=60, null=True)),
                ('funding', models.CharField(blank=True, max_length=60, null=True)),
                ('id_card', models.CharField(blank=True, max_length=60, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('object', models.CharField(blank=True, max_length=40, null=True)),
                ('tokenization_method', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapp.CCRequest')),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapp.ChargeResponse')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.CharField(blank=True, max_length=50, null=True)),
                ('token_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('livemode', models.BooleanField()),
                ('object', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('used', models.BooleanField()),
                ('cc_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapp.CreditCardInfo')),
            ],
        ),
        migrations.AddField(
            model_name='chargeresponse',
            name='c_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapp.CreditCardInfo'),
        ),
        migrations.CreateModel(
            name='ChargeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripeapp.CreditCardToken', to_field='token_id')),
            ],
        ),
    ]
